[package]
name = "hace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
captrs = "0.3.1"
enigo = "0.0.14"
process-memory = "0.4.0"
rand = "0.8.5"
sysinfo = "0.23.2"
